# Generated by Django 6.0.1 on 2026-01-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_blacklistedtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
