# Generated by Django 6.0.1 on 2026-01-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_all_users", "Может видеть всех пользователей"),
                    ("can_delete_user", "Может удалять пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
